export const get_currencies = ()=>{
  return [
    {
      "id": 29,
      "name": "نم",
      "small_name": "XEM",
      "small_name_slug": "XEM",
      "fix_buy_price": 0.1891,
      "fix_sell_price": 0.1891,
      "decimal": 0,
      "fix_fee_buy": 0,
      "fix_fee_sell": 0,
      "fee_buy": 0,
      "fee_sell": 0,
      "min_buy_amount": 1,
      "min_sell_amount": 1,
      "withdrawFee": 1,
      "is_name_tag": false,
      "is_stablecoin": false,
      "network": "Nem"
    },
    {
      "id": 28,
      "name": "تزوس",
      "small_name": "XTZ",
      "small_name_slug": "XTZ",
      "fix_buy_price": 6.867,
      "fix_sell_price": 6.867,
      "decimal": 0,
      "fix_fee_buy": 0,
      "fix_fee_sell": 0,
      "fee_buy": 0,
      "fee_sell": 0,
      "min_buy_amount": 1,
      "min_sell_amount": 1,
      "withdrawFee": 1,
      "is_name_tag": false,
      "is_stablecoin": false,
      "network": "Tezos"
    },
    {
      "id": 27,
      "name": "اتریوم کلاسیک",
      "small_name": "ETC",
      "small_name_slug": "ETC",
      "fix_buy_price": 58.54,
      "fix_sell_price": 58.54,
      "decimal": 0,
      "fix_fee_buy": 0,
      "fix_fee_sell": 0,
      "fee_buy": 0,
      "fee_sell": 0,
      "min_buy_amount": 1,
      "min_sell_amount": 1,
      "withdrawFee": 1,
      "is_name_tag": false,
      "is_stablecoin": false,
      "network": "Ethereum classic"
    },
    {
      "id": 26,
      "name": "وی چین",
      "small_name": "VET",
      "small_name_slug": "VET",
      "fix_buy_price": 0.11975,
      "fix_sell_price": 0.11975,
      "decimal": 5,
      "fix_fee_buy": 0,
      "fix_fee_sell": 0,
      "fee_buy": 0,
      "fee_sell": 0,
      "min_buy_amount": 1,
      "min_sell_amount": 1,
      "withdrawFee": 1,
      "is_name_tag": false,
      "is_stablecoin": false,
      "network": "VeChain"
    },
    {
      "id": 25,
      "name": "بیت تورنت",
      "small_name": "BTT",
      "small_name_slug": "BTT",
      "fix_buy_price": 0.00407,
      "fix_sell_price": 0.00407,
      "decimal": 0,
      "fix_fee_buy": 0,
      "fix_fee_sell": 0,
      "fee_buy": 0,
      "fee_sell": 0,
      "min_buy_amount": 1,
      "min_sell_amount": 1,
      "withdrawFee": 1,
      "is_name_tag": false,
      "is_stablecoin": false,
      "network": "TRC20"
    },
    {
      "id": 24,
      "name": "ریف",
      "small_name": "REEF",
      "small_name_slug": "REEF",
      "fix_buy_price": 0.02428,
      "fix_sell_price": 0.02428,
      "decimal": 0,
      "fix_fee_buy": 0,
      "fix_fee_sell": 0,
      "fee_buy": 0,
      "fee_sell": 0,
      "min_buy_amount": 1,
      "min_sell_amount": 1,
      "withdrawFee": 1,
      "is_name_tag": false,
      "is_stablecoin": false,
      "network": "ERC20"
    },
    {
      "id": 23,
      "name": "شیبا",
      "small_name": "SHIB",
      "small_name_slug": "SHIB",
      "fix_buy_price": 0.00001,
      "fix_sell_price": 0.00001,
      "decimal": 0,
      "fix_fee_buy": 0,
      "fix_fee_sell": 0,
      "fee_buy": 0,
      "fee_sell": 0,
      "min_buy_amount": 1,
      "min_sell_amount": 1,
      "withdrawFee": 1,
      "is_name_tag": false,
      "is_stablecoin": false,
      "network": "ERC20"
    },
    {
      "id": 21,
      "name": "لینک",
      "small_name": "LINK",
      "small_name_slug": "LINK",
      "fix_buy_price": 31.18,
      "fix_sell_price": 31.18,
      "decimal": 0,
      "fix_fee_buy": 0,
      "fix_fee_sell": 0,
      "fee_buy": 0,
      "fee_sell": 0,
      "min_buy_amount": 1,
      "min_sell_amount": 1,
      "withdrawFee": 1,
      "is_name_tag": false,
      "is_stablecoin": false,
      "network": "ERC20"
    },
    {
      "id": 20,
      "name": "لایت کوین",
      "small_name": "LTC",
      "small_name_slug": "LTC",
      "fix_buy_price": 192.3,
      "fix_sell_price": 192.3,
      "decimal": 0,
      "fix_fee_buy": 0,
      "fix_fee_sell": 0,
      "fee_buy": 0,
      "fee_sell": 0,
      "min_buy_amount": 1,
      "min_sell_amount": 1,
      "withdrawFee": 1,
      "is_name_tag": false,
      "is_stablecoin": false,
      "network": "Litecoin"
    },
    {
      "id": 19,
      "name": "بیت کوین کش",
      "small_name": "BCH",
      "small_name_slug": "BCH",
      "fix_buy_price": 641.1,
      "fix_sell_price": 641.1,
      "decimal": 0,
      "fix_fee_buy": 0,
      "fix_fee_sell": 0,
      "fee_buy": 0,
      "fee_sell": 0,
      "min_buy_amount": 1,
      "min_sell_amount": 1,
      "withdrawFee": 1,
      "is_name_tag": false,
      "is_stablecoin": false,
      "network": "Bitcoin cash"
    },
    {
      "id": 18,
      "name": "پولکادات",
      "small_name": "DOT",
      "small_name_slug": "DOT",
      "fix_buy_price": 35.44,
      "fix_sell_price": 35.44,
      "decimal": 0,
      "fix_fee_buy": 0,
      "fix_fee_sell": 0,
      "fee_buy": 0,
      "fee_sell": 0,
      "min_buy_amount": 1,
      "min_sell_amount": 1,
      "withdrawFee": 1,
      "is_name_tag": false,
      "is_stablecoin": false,
      "network": "Polkadot"
    },
    {
      "id": 17,
      "name": "ریپل",
      "small_name": "XRP",
      "small_name_slug": "XRP",
      "fix_buy_price": 1.108,
      "fix_sell_price": 1.108,
      "decimal": 0,
      "fix_fee_buy": 0,
      "fix_fee_sell": 0,
      "fee_buy": 0,
      "fee_sell": 0,
      "min_buy_amount": 1,
      "min_sell_amount": 1,
      "withdrawFee": 1,
      "is_name_tag": true,
      "is_stablecoin": false,
      "network": "Ripple"
    },
    {
      "id": 16,
      "name": "بایننس کوین",
      "small_name": "BNB",
      "small_name_slug": "BNB",
      "fix_buy_price": 425.5,
      "fix_sell_price": 425.5,
      "decimal": 2,
      "fix_fee_buy": 0,
      "fix_fee_sell": 0,
      "fee_buy": 0,
      "fee_sell": 0,
      "min_buy_amount": 1,
      "min_sell_amount": 1,
      "withdrawFee": 1,
      "is_name_tag": false,
      "is_stablecoin": false,
      "network": "ERC20"
    },
    {
      "id": 15,
      "name": "اتریوم",
      "small_name": "ETH",
      "small_name_slug": "ETH",
      "fix_buy_price": 3599.79,
      "fix_sell_price": 3599.79,
      "decimal": 6,
      "fix_fee_buy": 0,
      "fix_fee_sell": 0,
      "fee_buy": 0,
      "fee_sell": 0,
      "min_buy_amount": 1,
      "min_sell_amount": 1,
      "withdrawFee": 1,
      "is_name_tag": false,
      "is_stablecoin": false,
      "network": "ERC20"
    },
    {
      "id": 14,
      "name": "تتر ترون",
      "small_name": "USDT",
      "small_name_slug": "USDT",
      "fix_buy_price": 1,
      "fix_sell_price": 1,
      "decimal": 1,
      "fix_fee_buy": 2,
      "fix_fee_sell": 2,
      "fee_buy": 3,
      "fee_sell": 3,
      "min_buy_amount": 1,
      "min_sell_amount": 1,
      "withdrawFee": 1,
      "is_name_tag": false,
      "is_stablecoin": true,
      "network": "TRC20"
    },
    {
      "id": 13,
      "name": "ترون",
      "small_name": "TRX",
      "small_name_slug": "TRX",
      "fix_buy_price": 0.11587,
      "fix_sell_price": 0.11587,
      "decimal": 0,
      "fix_fee_buy": 5,
      "fix_fee_sell": 2,
      "fee_buy": 2,
      "fee_sell": 2,
      "min_buy_amount": 2,
      "min_sell_amount": 10000000,
      "withdrawFee": 1,
      "is_name_tag": false,
      "is_stablecoin": false,
      "network": "TRX"
    },
    {
      "id": 12,
      "name": "تومان",
      "small_name": "IRT",
      "small_name_slug": "IRT",
      "fix_buy_price": 27637,
      "fix_sell_price": 27640,
      "decimal": 0,
      "fix_fee_buy": 5000,
      "fix_fee_sell": 5000,
      "fee_buy": 3,
      "fee_sell": 3,
      "min_buy_amount": 1,
      "min_sell_amount": 1,
      "withdrawFee": 1,
      "is_name_tag": false,
      "is_stablecoin": true,
      "network": null
    },
    {
      "id": 11,
      "name": "تتر اتریوم",
      "small_name": "USDT",
      "small_name_slug": "USDT",
      "fix_buy_price": 1,
      "fix_sell_price": 1,
      "decimal": 1,
      "fix_fee_buy": 1,
      "fix_fee_sell": 0,
      "fee_buy": 1,
      "fee_sell": 1,
      "min_buy_amount": 10,
      "min_sell_amount": 10,
      "withdrawFee": 1,
      "is_name_tag": false,
      "is_stablecoin": false,
      "network": "ERC20"
    },
    {
      "id": 10,
      "name": "دوج کوین",
      "small_name": "dogecoin",
      "small_name_slug": "DOGE",
      "fix_buy_price": 0.2438,
      "fix_sell_price": 0.2438,
      "decimal": 0,
      "fix_fee_buy": 0,
      "fix_fee_sell": 0,
      "fee_buy": 10,
      "fee_sell": 10,
      "min_buy_amount": 100,
      "min_sell_amount": 100,
      "withdrawFee": 1,
      "is_name_tag": false,
      "is_stablecoin": false,
      "network": "DOGECOIN"
    },
    {
      "id": 9,
      "name": "بیت کوین",
      "small_name": "bitcoin",
      "small_name_slug": "BTC",
      "fix_buy_price": 47877.79,
      "fix_sell_price": 47877.79,
      "decimal": 6,
      "fix_fee_buy": 0.0005,
      "fix_fee_sell": 0,
      "fee_buy": 3.5,
      "fee_sell": 3.5,
      "min_buy_amount": 0.0001,
      "min_sell_amount": 0.0001,
      "withdrawFee": 1,
      "is_name_tag": false,
      "is_stablecoin": false,
      "network": "BTC"
    }]
  
}